name: cfdemo
dependencies:
- appnope=0.1.0=py35_0
- backports.shutil_get_terminal_size=1.0.0=py35_0
- blas=1.1=openblas
- click=6.6=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- flask=0.11.1=py35_0
- freetype=2.6.3=1
- h5py=2.6.0=np111py35_4
- hdf5=1.8.17=2
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_2
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.1.5=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- jpeg=9b=0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.3.0=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libgcc=4.8.5=1
- libpng=1.6.23=0
- libtiff=4.0.6=5
- markupsafe=0.23=py35_2
- matplotlib=1.5.2=np111py35_3
- mistune=0.7.3=py35_0
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- nose=1.3.7=py35_1
- notebook=4.2.1=py35_0
- numpy=1.11.0=py35_blas_openblas_201
- openblas=0.2.18=2
- openssl=1.0.2h=1
- pandas=0.18.1=np111py35_0
- pexpect=4.1.0=py35_0
- pickleshare=0.7.2=py35_0
- pillow=3.2.0=py35_2
- pip=8.1.2=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_3
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- python-decorator=4.0.10=py35_0
- python-simplegeneric=0.8.1=py35_0
- python.app=1.2=py35_4
- pytz=2016.4=py35_0
- pyzmq=15.2.0=py35_1
- qt=4.8.7=3
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- redis=3.2.0=0
- scikit-learn=0.17.1=np111py35_blas_openblas_200
- scipy=0.17.1=np111py35_blas_openblas_200
- setuptools=23.0.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- terminado=0.6=py35_0
- tk=8.5.19=0
- tornado=4.3=py35_1
- traitlets=4.2.2=py35_0
- werkzeug=0.11.10=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.3=py35_1
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - keras==1.0.5
  - mockredispy==2.9.3
  - pyyaml==3.11
  - simplegeneric==0.8.1
  - theano==0.9.0.dev1

