---
resources:
- name: cf-demo-testing
  type: git
  source:
    uri: git@github.com:datitran/cf-demo.git
    branch: master
    private_key: {{private-key}}

- name: cf-demo-production
  type: git
  source:
    uri: git@github.com:datitran/cf-demo.git
    branch: master
    private_key: {{private-key}}
    tag_filter: "v*"

- name: pcfdev-testing
  type: cf
  source:
    api: {{cf-api-testing}}
    username: {{cf-username-testing}}
    password: {{cf-password-testing}}
    organization: {{cf-organization-testing}}
    space: {{cf-space-testing}}
    skip_cert_check: true

- name: pcfdev-production
  type: cf
  source:
    api: {{cf-api-production}}
    username: {{cf-username-production}}
    password: {{cf-password-production}}
    organization: {{cf-organization-production}}
    space: {{cf-space-production}}
    skip_cert_check: true

jobs:
- name: run-test-predict-app
  plan:
  - get: cf-demo-testing
    trigger: true
  - get: cf-demo-production
    trigger: false

  - task: run-and-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: datitran/cf-demo
      inputs:
      - name: cf-demo-testing
      run:
        path: cf-demo-testing/run_tests.sh

- name: deploy-predict-app-testing
  plan:
    - get: cf-demo-testing
      trigger: true
      passed: [run-test-predict-app]
    - put: pcfdev-testing
      params:
        manifest: cf-demo-testing/src/python/project/prediction_app/manifest_test.yml
        path: cf-demo-testing/src/python/project/prediction_app/

- name: deploy-predict-app-production
  plan:
    - get: cf-demo-production
      trigger: false
      passed: [run-test-predict-app]
    - put: pcfdev-production
      params:
        manifest: cf-demo-production/src/python/project/prediction_app/manifest_prod.yml
        path: cf-demo-production/src/python/project/prediction_app/

- name: deploy-sketch-app-testing
  plan:
    - get: cf-demo-testing
      trigger: true
      passed: [deploy-predict-app-testing]
    - put: pcfdev-testing
      params:
        manifest: cf-demo-testing/src/ruby/project/sketch_app/manifest_test.yml
        path: cf-demo-testing/src/ruby/project/sketch_app/

- name: deploy-sketch-app-production
  plan:
    - get: cf-demo-production
      trigger: false
      passed: [deploy-predict-app-production]
    - put: pcfdev-production
      params:
        manifest: cf-demo-production/src/ruby/project/sketch_app/manifest_prod.yml
        path: cf-demo-production/src/ruby/project/sketch_app/
